package(default_visibility = ["//visibility:public"])

filegroup(name = "sources", srcs = glob(["*.mjs", "*.sh", "*.json"]))

sh_binary(
    name = "run",
    srcs = ["run.sh"],
    data = [":sources"],
    tags = ["manual", "local"],
)

sh_test(
    name = "unit",
    srcs = ["unit.sh"],
    data = [":sources"],
    tags = ["local"],
    timeout = "short",
)
